### ISSUE TITLE
first error

### ISSUE THREAD

**Issue by duncanjoly13** [fishnexj/personal-finance-data-analysis-templates#1]
After entering folderPath and filePath (don't know what those are supposed to be so I've tried multiple folderPaths)

`Measure
Loading blocked by failures with other queries.
Visual Data Model
The key didn't match any rows in the table.`

**Comment by fishnexj** [comment]
As an example, here are the variables I used for my folderPath...
`C:\Users\<userName>\Financial`

...and filePath...
`FileName.xlsx`

Once you have those in the Power BI file will connect to the Finance Excel template and pull the relevant tables.

Have you changed any table names in the Excel file?

**Comment by duncanjoly13** [comment]
error quashed, thanks. I was writing the wrong filePath, thinking that it referred to the .pbit instead of the Excel database
